name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Run tests
      env:
        CARDGEN_SECRET: "release-test-secret"
      run: go test ./...

    - name: Build binaries
      run: |
        # Linux amd64
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o cardgen-pro-linux-amd64 ./cmd/cardgen-pro
        
        # Linux arm64
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o cardgen-pro-linux-arm64 ./cmd/cardgen-pro
        
        # macOS amd64
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o cardgen-pro-darwin-amd64 ./cmd/cardgen-pro
        
        # macOS arm64 (Apple Silicon)
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o cardgen-pro-darwin-arm64 ./cmd/cardgen-pro
        
        # Windows amd64
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o cardgen-pro-windows-amd64.exe ./cmd/cardgen-pro

    - name: Create checksums
      run: |
        sha256sum cardgen-pro-* > checksums.txt

    - name: Extract version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          cardgen-pro-linux-amd64
          cardgen-pro-linux-arm64
          cardgen-pro-darwin-amd64
          cardgen-pro-darwin-arm64
          cardgen-pro-windows-amd64.exe
          checksums.txt
        body: |
          ## cardgen-pro ${{ steps.version.outputs.VERSION }}
          
          Card Data & ISO-8583 Test Suite for sandbox/development environments.
          
          ### Installation
          
          Download the appropriate binary for your platform and make it executable:
          
          ```bash
          # Linux/macOS
          chmod +x cardgen-pro-*
          mv cardgen-pro-* /usr/local/bin/cardgen-pro
          
          # Verify
          cardgen-pro version
          ```
          
          ### Quick Start
          
          ```bash
          export CARDGEN_SECRET="your-dev-secret"
          cardgen-pro generate --brand visa --count 10 --out cards.json
          ```
          
          ### What's Changed
          
          See [CHANGELOG.md](https://github.com/felipemacedo1/cardgen-pro/blob/main/CHANGELOG.md) for details.
          
          ### ⚠️ Security Warning
          
          **TEST/SANDBOX USE ONLY** - Do not use in production environments.
          
          See [SECURITY.md](https://github.com/felipemacedo1/cardgen-pro/blob/main/SECURITY.md) for security guidelines.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: felipemacedo/cardgen-pro
        tags: |
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
